name: Java CI with Gradle

on:
  push:
    branches: [ "main", "CICD-2", "CICD" ]
    paths:
      - "Final-Project/apps/java-backend/**"
      - ".github/workflows/gradle.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "Final-Project/apps/java-backend/**"
      - ".github/workflows/gradle.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Run Gradle tests
        run: |
          cd Final-Project/apps/java-backend
          ./gradlew test
          # If you want a stricter check, you can use:
          # ./gradlew check
          # or, if you really want everything:
          # ./gradlew build
